on: [push]

name: Python Checks

jobs:
  build:
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python        
        poetry install --no-dev
        pip install flake8
        pip install safety
        pip install PyLint
        
    - name: Flake8
      run: |
        flake8 .

    - name: PyLint
      run: |
        find ./routers/ -type f -name "*.py" | xargs pylint --rcfile ./.pylintrc

    - name: PipCheck
      run: |
        pip check

    - name: PipCheck
      run: |
        safety check -r requirements.txt